name: navigation
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../core'

  settings:
    path: '../settings'

  map:
    path: '../map'

  # Location - https://pub.dev/packages/geolocator
  geolocator: ^9.0.0

  # HTTP - https://pub.dev/packages/http
  http: ^0.13.4

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.1

  # Map launcher - https://pub.dev/packages/map_launcher
  map_launcher: ^2.2.3

  # URL Launcher - https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.3

  # Collection - https://github.com/dart-lang/collection
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

