name: navigation
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: '../core'

  settings:
    path: '../settings'

  map:
    path: '../map'

  # Location - https://pub.dev/packages/geolocator
  geolocator: ^11.0.0

  # HTTP - https://pub.dev/packages/http
  http: ^1.2.1

  # BLoC - https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.4

  # Map launcher - https://pub.dev/packages/map_launcher
  map_launcher: ^3.2.0

  # URL Launcher - https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.5

  # Collection - https://pub.dev/packages/collection
  collection: ^1.18.0

dependency_overrides:
  # Force `package_info_plus` using newest `web` version (see: https://github.com/fluttercommunity/plus_plugins/issues/2653)
  web: ^0.5.0

  # Force `flutter_localizations` using newest `intl`
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

