name: tankste
description: Finde die günstigste Tankstelle in deiner Nähe!
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  station:
    path: './station'

  # Google Maps - https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.1.8

  # HTTP - https://pub.dev/packages/http
  http: ^0.13.4

  # Font Awesome - https://pub:dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.1.0

  # URL Launcher - https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.3

  # Package Info - https://pub.dev/packages/package_info_plus
  package_info_plus: ^1.4.2

  # Location - https://pub.dev/packages/geolocator
  geolocator: ^9.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/markers/
