name: review
publish_to: none

environment:
  sdk: 3.12.2
  flutter: 3.44.2

dependencies:
  flutter:
    sdk: flutter

  review_core:
    path: '../core'

  review_impl:
    path: '../impl_closed'

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

