[versions]
agp = "9.4.0"
flutterPluginLoader = "1.0.0"
kotlin = "2.4.20"
#androidx-core = "1.19.0"
#kotlinx-coroutines = "1.11.0"
compose = "2026.08.00"
workRuntimeKtx = "2.11.2"
material3 = "1.4.0"
material = "1.14.0"
[libraries]
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#compose-navigation = "2.10.0"
#androidx-activity = "1.13.0"
#appcompat = "1.8.0"
#jetbrainsKotlinJvm = "2.4.10"
#serialization = "1.11.0"
#ktor = "3.5.2"
#androidxLifecycleViewModel = "2.11.0"
#junit = "4.13.2"
#mockk = "1.14.11"
#turbine = "1.2.1"
#maven-publish = "0.37.0"
#dokka = "2.2.0"
#
#[libraries]
#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
#androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycleViewModel" }
#
#androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
#kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
#kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
#kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
#
## Ktor
#ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
#ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
#ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
#ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Compose
#compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
#compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
#compose-ui = { group = "androidx.compose.ui", name = "ui" }
#compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#compose-material3 = { group = "androidx.compose.material3", name = "material3" }
#compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
#compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }

## Testing
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
#mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
#kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
#turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine"}
#
#[bundles]
#compose = ["compose-ui", "compose-ui-tooling", "compose-ui-tooling-preview", "compose-material3", "compose-material-icons", "compose-navigation"]
#ktor = ["ktor-client-android", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json", "ktor-client-logging"]
#
[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
#kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#flutter-plugin-loader = { id = "dev.flutter.flutter-plugin-loader", version.ref = "flutterPluginLoader" }
#jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
#dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
